version: '3'
services:
  node.omne:
    build:
      context: .
      dockerfile: Dockerfile
    image: open-node:latest
    container_name: node_placeholder.omne
    ports:
      - "3401:3400"
    networks:
      - node_one_omne-net
    volumes:
      - ./app:/app
    labels:
      app: node-two
      level: blockchain
      role: validator
      tier: backend
      track: continuous
    environment:
      - PYTHONPATH=/app
    stdin_open: true
    tty: true

networks:
  node_one_omne-net:
    external: true