version: "3.8"

services:
  node.omne.open:
    build: 
      context: .
      dockerfile: Dockerfile.open_node  # Using Dockerfile.open_node for open‑source node
    image: omne-node:open-source
    container_name: node.omne.open
    ports:
      - "${OPEN_HOST_PORT:-3401}:3400"  # Maps host port (defaults to 3401 if OPEN_HOST_PORT is not set) to container port 3400
    networks:
      - omne_node_eaies-net
      - omne_node_hash-api-net
    volumes:
      - ./app:/app
    labels:
      app: omne-node-open
      level: blockchain
      role: participant
      tier: backend
      track: continuous
    environment:
      - NETWORK_SUFFIX=development
      - PYTHONPATH=/app
      - NODE_ENV=development
      - PORT_NUMBER=${PORT_NUMBER:-3400}
      - NODE_ID=N2RlNmY0
      - STEWARD_ADDRESS=${STEWARD_ADDRESS}  # Must be provided by the user (no default)
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "4G"
        reservations:
          cpus: "1.0"
          memory: "2G"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3400/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  omne_node_eaies-net:
    external: true
  omne_node_hash-api-net:
    external: true
