version: '3'
services:
  node.omne:
    build:
      context: .
      dockerfile: Dockerfile
    image: open-node:latest
    container_name: node.omne
    ports:
      - "3400:3400"
    networks:
      - node_one_omne-net
    volumes:
      - ./app:/app
    labels:
      app: node-one
      level: blockchain
      role: validator
      tier: backend
      track: continuous
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}

networks:
  node_one_omne-net:
    external: true
