version: '3'
services:
  node1.omne:
    build:
      context: .
      dockerfile: Dockerfile
    image: omne-node:latest
    container_name: node1.omne
    ports:
      - "3401:3400"
    networks:
      - node_one_omne-net
      - node_one_hash-api-net
    volumes:
      - ./app:/app
    labels:
      app: omne-node
      level: blockchain
      role: validator
      tier: backend
      track: continuous
    environment:
      - PYTHONPATH=/app
      - STEWARD_ADDRESS=${STEWARD_ADDRESS}

networks:
  node_one_omne-net:
    external: true
  node_one_hash-api-net:
    external: true
